### ISSUE TITLE
missing RSVP module

### ISSUE THREAD

**Issue by juwara0** [ciena-blueplanet/ember-cli-visual-acceptance#103]
### Problem:
Upon a fresh clone, `npm install` and `ember serve` or `ember test` of an addon with `ember-cli-visual-acceptance` as a dependency a missing module error for RSVP is being thrown.

```
Cannot find module 'rsvp'
Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Micarrol/Devel/ember-frost-popover/node_modules/ember-cli-visual-acceptance/lib/utils.js:6:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by EWhite613** [comment]
Sorry for the late reply, school etc.

I don't remember adding that module (I believe I was relying on newer versions of node support. But maybe i did, been a while).

Maybe @ro0gr knows? I believe it's this [module](https://github.com/tildeio/rsvp.js/), and maybe forgot to add? But I see we already have [es6-promise](https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/blob/master/package.json#L53) and can just switch the usage to `var Promise = require('es6-promise').Promise;`
