### ISSUE TITLE
`Cannot find module 'sync-request'` and `Cannot find module 'es6-promise'`

### ISSUE THREAD

**Issue by briangonzalez** [ciena-blueplanet/ember-cli-visual-acceptance#113]
When running `ember install ember-cli-visual-acceptance`, I get the following errors:

```
Cannot find module 'sync-request'
```

as well as..

```
Cannot find module 'es6-promise'
```

I think you need to make them `dependencies` and not `devDependencies`. Thanks.

**Comment by notmessenger** [comment]
In my `devDependencies` I have `"ember-cli-visual-acceptance": "^2.2.0"`.  After clearing out _node_modules_ and doing a fresh `npm install` I got this error when running `ember s`:

```
$ ember s
Cannot find module 'sync-request'
Error: Cannot find module 'sync-request'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jerbrown/Documents/Development/Code/repos/notmessenger/forks/ember-frost-popover/node_modules/ember-cli-visual-acceptance/index.js:6:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

When I then ran `ember g ember-cli-visual-acceptance` I received the same error again.

**Comment by EWhite613** [comment]
hmmm  it should be added in the blueprints https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/blob/master/blueprints/ember-cli-visual-acceptance/index.js#L12-L20

**Comment by notmessenger** [comment]
They should also be listed in the `dependencies` of _package.json_.  Purely from an install perspective you could actually argue that the entries do not need to be in the blueprint and only in the `dependencies`.

**Comment by EWhite613** [comment]
New build should be out in ~5 min
